name: "Build and Test API"

on: [push, pull_request]

env:
  PORT: 3000
  DATABASE_URL: postgresql://postgres:1234@localhost:5432/test?schema=public
  JWT_SEED: this_is_a_test_secret_value_for_jwt
  SEND_EMAIL: true
  MAILER_SERVICE: gmail
  MAILER_EMAIL: sistemabasesdedatos1@gmail.com
  MAILER_SECRET_KEY: ldhsyzllaxfsxmyh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npx prisma migrate deploy
        env:
          DATABASE_URL: postgresql://postgres:1234@localhost:5432/test
      - run: npm run test:git
        env:
          DATABASE_URL: postgresql://postgres:1234@localhost:5432/test
